
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async clipboardRead() : Promise<Result<ClipboardReadResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clipboard_read") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clipboardWriteText(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clipboard_write_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clipboardWriteFiles(paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clipboard_write_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clipboardWriteImage(png: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clipboard_write_image", { png }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notify(opts: NotificationOptions) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notify", { opts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notificationPermissionState() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notification_permission_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async notificationRequestPermission() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("notification_request_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hotkeyRegister(appId: string, combo: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hotkey_register", { appId, combo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hotkeyUnregister(appId: string, combo: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hotkey_unregister", { appId, combo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hotkeyIsRegistered(appId: string, combo: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hotkey_is_registered", { appId, combo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsReadText(appId: string, relPath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_read_text", { appId, relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsReadBytes(appId: string, relPath: string) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_read_bytes", { appId, relPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsWriteText(appId: string, relPath: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_write_text", { appId, relPath, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsWriteBytes(appId: string, relPath: string, contents: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_write_bytes", { appId, relPath, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async autostartIsEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("autostart_is_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async autostartSet(enabled: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("autostart_set", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Physical bounds the overlay window covers (virtual desktop minus taskbar strip).
 */
async monitorOverlayBounds() : Promise<Bounds> {
    return await TAURI_INVOKE("monitor_overlay_bounds");
},
/**
 * Physical bounds of the combined virtual desktop (all monitors unioned).
 */
async monitorVirtualDesktopBounds() : Promise<Bounds> {
    return await TAURI_INVOKE("monitor_virtual_desktop_bounds");
},
async modsReadAutoloadIds() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mods_read_autoload_ids") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async modsSetAutoloadIds(ids: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mods_set_autoload_ids", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Base URL (loopback) of the running mod server: `http://127.0.0.1:<port>`.
 */
async modsBaseUrl() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mods_base_url") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async modsList() : Promise<Result<InstalledMod[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mods_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async modsInstall(path: string, forceReplace: boolean) : Promise<Result<InstallResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mods_install", { path, forceReplace }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async elxrPeek(path: string) : Promise<Result<ElxrPeek, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("elxr_peek", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * On-demand foreground window snapshot.
 */
async foregroundWindow() : Promise<Result<ForegroundWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("foreground_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbExecute(appId: string, sql: string, params: DbValue[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_execute", { appId, sql, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbQuery(appId: string, sql: string, params: DbValue[]) : Promise<Result<QueryResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_query", { appId, sql, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dbIsAppRegistered(appId: string) : Promise<boolean> {
    return await TAURI_INVOKE("db_is_app_registered", { appId });
},
async audioStartRecording(appId: string, options: AudioOptions | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_start_recording", { appId, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioStopRecording(appId: string) : Promise<Result<RecordedAudio, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("audio_stop_recording", { appId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async audioIsRecording(appId: string) : Promise<boolean> {
    return await TAURI_INVOKE("audio_is_recording", { appId });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
audioLevel: AudioLevel,
cursorMoved: CursorMoved,
elxrOpen: ElxrOpen,
engineSecondInstance: SecondInstance,
foregroundChanged: ForegroundChanged,
hotkeyPressed: HotkeyPressed
}>({
audioLevel: "audio:level",
cursorMoved: "cursor-moved",
elxrOpen: "elxr:open",
engineSecondInstance: "engine:second-instance",
foregroundChanged: "foreground-changed",
hotkeyPressed: "hotkey-pressed"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * RMS-derived 0..1 level meter, emitted ~20x/sec while recording.
 */
export type AudioLevel = { app_id: string; level: number; peak: number }
export type AudioOptions = { sample_rate?: number; channels?: number }
export type Bounds = { x: number; y: number; width: number; height: number }
/**
 * Discriminated clipboard snapshot. Serde shape (internally tagged on `kind`):
 * `{ kind: "image", png } | { kind: "files", paths } | { kind: "text", text, sourceUrl } | { kind: "empty" }`.
 */
export type ClipboardReadResult = { kind: "image"; png: number[] } | { kind: "files"; paths: string[] } | { kind: "text"; text: string; sourceUrl: string | null } | { kind: "empty" }
/**
 * Global cursor position in CSS pixels relative to the overlay window's top-left.
 * Mirrors the `CursorPosition` payload hit-regions-rs emits; declared here so the
 * type is in `bindings.ts`. The event itself is emitted by hit-regions-rs' poll thread.
 */
export type CursorMoved = { x: number; y: number }
/**
 * A specta-friendly SQL value. `Array`/`Object` exist for API completeness but
 * are rejected as bind params by sqlite.
 */
export type DbValue = null | number | string | number[] | DbValue[] | Partial<{ [key in string]: DbValue }>
/**
 * A `.elxr` file was opened (double-click) and its manifest peeked.
 */
export type ElxrOpen = { path: string; manifest: ModManifest; iconDataUrl?: string | null; sizeBytes: number }
/**
 * Result of peeking inside a `.elxr` before unpacking.
 */
export type ElxrPeek = { manifest: ModManifest; iconDataUrl?: string | null; sizeBytes: number }
/**
 * The currently-active (foreground) window; emitted only on change (~250 ms poll).
 */
export type ForegroundChanged = { window: ForegroundWindow }
/**
 * Snapshot of the currently-active (foreground) window: title + owning process +
 * fullscreen state. Produced by `window_info` (Task 3); declared here because
 * events is the compile-order-first module.
 */
export type ForegroundWindow = { title: string; process_name: string; process_id: number; is_fullscreen: boolean; is_engine_window: boolean }
/**
 * A registered global hotkey was pressed; payload is the owning app id + normalized combo.
 */
export type HotkeyPressed = { app_id: string; combo: string }
export type InstallResult = { manifest: ModManifest; entryUrl: string }
export type InstalledMod = { id: string; name: string; entry: string; version?: string | null; author?: string | null; icon?: string | null; iconUrl?: string | null; description?: string | null; entryUrl: string }
/**
 * A mod's `manifest.json`.
 */
export type ModManifest = { id: string; name: string; version?: string | null; author?: string | null; icon?: string | null; description?: string | null; entry?: string }
export type NotificationOptions = { title: string; body: string }
export type QueryResult = { columns: string[]; rows: DbValue[][] }
/**
 * Output WAV is always mono/16k; the fields reflect the file (16000/1).
 */
export type RecordedAudio = { wav_bytes: number[]; duration_ms: number; peak: number; sample_rate: number; channels: number }
/**
 * Fired by the single-instance plugin callback when a second launch occurs.
 */
export type SecondInstance = { argv: string[]; cwd: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
